version: '3.8'
services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - ./api-gateway:/app
      - /app/node_modules
    command: npm run start:dev
    environment:
      - NODE_ENV=development
      - AUTH_SERVICE_URL=http://auth-service:3001
      - COURSE_SERVICE_URL=http://course-service:3000
    depends_on:
      - auth-service
      - course-service
    networks:
      - aladia-net

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./auth-service:/app
      - /app/node_modules
    command: npm run start:dev
    environment:
      - MONGODB_URI=mongodb://mongo:27017/auth_service
      - JWT_ACCESS_SECRET=your_super_secret_access_key_min_32_chars_123
      - JWT_REFRESH_SECRET=your_super_secret_refresh_key_min_32_chars_123
      - PORT=3001
      - NODE_ENV=development
    depends_on:
      - mongo
    networks:
      - aladia-net

  course-service:
    build:
      context: ./course-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./course-service:/app
      - /app/node_modules
    command: npm run start:dev
    environment:
      - MONGODB_URI=mongodb://mongo:27017/course_service
      - REDIS_URL=redis://redis:6379
      - PORT=3000
      - NODE_ENV=development
    depends_on:
      - mongo
      - redis
    networks:
      - aladia-net

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - aladia-net

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongo
    networks:
      - aladia-net

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - aladia-net

  redis-commander:
    image: rediscommander/redis-commander:latest
    ports:
      - "8082:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    networks:
      - aladia-net

volumes:
  mongodb_data:
  redis_data:

networks:
  aladia-net:
    driver: bridge