services:
  course-service:
    build: ./course-service
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    networks:
      - aladia-net

  auth-service:
    build: ./auth-service
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/auth_service
      - JWT_ACCESS_SECRET=your_super_secret_access_key_min_32_chars_123
      - JWT_REFRESH_SECRET=your_super_secret_refresh_key_min_32_chars_123
      - PORT=3001
      - NODE_ENV=development
    depends_on:
      - mongo
    networks:
      - aladia-net

  api-gateway:
    build: ./api-gateway
    ports:
      - "3002:3002"
    depends_on:
      - course-service
      - auth-service
    networks:
      - aladia-net

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - aladia-net

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongo
    networks:
      - aladia-net

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - aladia-net

  redis-commander:
    image: rediscommander/redis-commander:latest
    ports:
      - "8082:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    networks:
      - aladia-net

volumes:
  mongodb_data:
  redis_data:

networks:
  aladia-net:
    driver: bridge